name: Utils
version: '${project.version}'
main: utils.Utils
api-version: 1.16
authors: [ Valless ]
depend:
  - spark
  - PlaceholderAPI
  - LuckPerms
commands:
  banipmask:
    permission: bans.banipmask